name: Run a full re3data dump
on:
  schedule:
    - cron:  '27 5 13 * *'

jobs:
  data-dump:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Test data dump with pytest
      run: |
        pytest tests/test_data_dump.py
